import { Injectable, Logger, BadRequestException, InternalServerErrorException, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../common/prisma/prisma.service';
import { CreateAthleteDto } from './dto/create-athlete.dto';
import { AthleteDto } from './dto/athlete.dto';
import { Prisma, AthleteCategory } from '@prisma/client';

@Injectable()
export class AthletesService {
    private readonly logger = new Logger(AthletesService.name);

    // Business Rules: Age Range per Category
    private readonly AGE_RULES: Record<AthleteCategory, { min: number; max: number }> = {
        [AthleteCategory.U14]: { min: 10, max: 13 },
        [AthleteCategory.U17]: { min: 14, max: 16 },
        [AthleteCategory.U19]: { min: 17, max: 19 },
    };

    constructor(private readonly prisma: PrismaService) { }

    async create(createAthleteDto: CreateAthleteDto): Promise<AthleteDto> {
        this.logger.log(`Creating athlete: ${createAthleteDto.name} (${createAthleteDto.category})`);

        // 1. Validate Age-Category Mapping
        const rules = this.AGE_RULES[createAthleteDto.category];
        if (createAthleteDto.age < rules.min || createAthleteDto.age > rules.max) {
            this.logger.warn(`Age mismatch: ${createAthleteDto.age} not valid for ${createAthleteDto.category}`);
            throw new BadRequestException(
                `Age ${createAthleteDto.age} does not match category ${createAthleteDto.category} (requires ${rules.min}-${rules.max})`
            );
        }

        // 2. Validate School Exists
        // Optimization: We could let the DB FK constraint fail, but explicit check 
        // allows for the specific "400 School not found" message requested (or 404).
        // Requirement said "400 if schoolId does not exist" -> Spec says 400 for business rules.
        const schoolExists = await this.prisma.school.findUnique({
            where: { id: createAthleteDto.schoolId },
            select: { id: true }
        });

        if (!schoolExists) {
            this.logger.warn(`School not found: ${createAthleteDto.schoolId}`);
            throw new BadRequestException('School not found');
        }

        // Log exact values for debugging duplicate issues
        this.logger.log(`Attempting to create athlete with exact values: name="${createAthleteDto.name}", age=${createAthleteDto.age} (type: ${typeof createAthleteDto.age}), schoolId="${createAthleteDto.schoolId}"`);

        try {
            const athlete = await this.prisma.athlete.create({
                data: {
                    name: createAthleteDto.name,
                    age: createAthleteDto.age,
                    gender: createAthleteDto.gender,
                    category: createAthleteDto.category,
                    schoolId: createAthleteDto.schoolId,
                    personalBest: createAthleteDto.personalBest,
                    // bibNumber is auto-generated by DB default(autoincrement())
                },
            });

            this.logger.log(`Athlete created: ${athlete.id}, Bib: ${athlete.bibNumber}`);
            return new AthleteDto(athlete);

        } catch (error) {
            if (error instanceof Prisma.PrismaClientKnownRequestError) {
                // Duplicate constraint violation (name + age + schoolId)
                if (error.code === 'P2002') {
                    // Log the exact fields that caused the duplicate
                    const fields = (error.meta?.target as string[]) || [];
                    this.logger.warn(`Duplicate athlete detected on fields: [${fields.join(', ')}]. Values: name="${createAthleteDto.name}", age=${createAthleteDto.age}, schoolId="${createAthleteDto.schoolId}"`);
                    throw new BadRequestException('Athlete with this name and age already registered for this school');
                }
            }

            this.logger.error(`Failed to create athlete: ${error instanceof Error ? error.message : 'Unknown'}`, error instanceof Error ? error.stack : undefined);
            throw new InternalServerErrorException('Failed to create athlete');
        }
    }
}
